### ISSUE TITLE
Monitoring non-.go files

### ISSUE THREAD

**Issue by kristen1980** [alexedwards/go-reload#6]
I have been using this and love it. However, it doesn't monitor changes I make in my html templates (*.html) or other non-.go files. Is there a reason for this?

**Comment by alexedwards** [comment]
The main reason is that inotifywait only offers an exclude pattern option (not an include pattern option), and I haven't spent the time to figure out a regexp that would correctly support multiple (negated)  extensions.

If there's a regexp that is clear and maintainable, then I'd be happy to use it instead of the current `--exclude '[^g][^o]$'` parameter. 

If not, then I think my preference would be to add an `-a` flag, which turns on watching of all files regardless of their extension. Do you think that would work?

**Comment by kristen1980** [comment]
a flag would be fine...I'm not good enough w/ regex to know what it would be. thx for the quick response!

**Comment by alexedwards** [comment]
I've added in a flag, so that specifying `-a` will result in all files in your GOPATH being watched for changes, regardless of their extension.

`$ go-reload -a main.go`

I've been trying it out myself over the past few days, and it seems to work fine.
